{% set name = "pretab" %}
{% set version = "0.0.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/OpenTabular/PreTab/archive/v{{ version }}.tar.gz
  sha256: 9a6a663521b2d2d39f9c5f0e777596fb391f103dc277cc79d7a96067f4b82ddd

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - pip
    - setuptools
  run:
    - python >={{ python_min }}
    - numpy
    - scikit-learn
    - scipy
    - pandas

test:
  imports:
    - pretab
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/OpenTabular/PreTab
  summary: A python package for preprocessing tabular data
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - jan-janssen
